"""Generate the AY scheduler, volume ROM and reset data for one 1024x9 EBR.

The internal microprogram shares a counter ALU between all generators.
No CPU software, DMA or external SRAM is used for audio.
"""
import argparse
from pathlib import Path

OPS = dict(low=0, high=1, countlow=2, counthigh=3, store=4, storehigh=5,
           tone=6, noise=7, envelope=8, mixer=9, volume=10, clear=11,
           sum=12, wait=13, envlow=14, envhigh=15)

def words():
    result = [0]*1024
    # Same logarithmic curve as the BK AY, max 3*127+128 beeper=509.
    result[32:48] = [0,1,2,3,4,6,8,12,16,23,32,45,64,80,101,127]
    program = []
    def emit(op, address=0):
        program.append(OPS[op]<<5 | address)
    for c in range(3):
        emit('low', c*2);emit('high', c*2+1)
        emit('countlow', 16+2*c);emit('counthigh', 17+2*c)
        emit('store', 16+2*c);emit('storehigh', 17+2*c);emit('tone', c)
    emit('low', 6);emit('countlow', 22);emit('counthigh', 23)
    emit('store', 22);emit('storehigh', 23);emit('noise')
    emit('envlow', 11);emit('envhigh', 12)
    emit('countlow', 24);emit('counthigh', 25);emit('envelope', 13)
    emit('store', 24);emit('storehigh', 25)
    emit('mixer', 7);emit('clear')
    for c in range(3):
        emit('volume', 8+c);emit('sum')
    emit('wait')
    assert len(program) == 43
    result[512:512+len(program)] = program
    return result

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', default='rtl/ay8910.mem')
    args = parser.parse_args()
    values = words()
    target = Path(args.output)
    target.write_text(''.join(f'{n:03x}\n' for n in values))
    # Each pair of nine-bit words occupies 18 physical bits in a 20-bit
    # INIT slot. Sixteen pairs per 320-bit Lattice INITVAL parameter.
    init = sum(n << (20*(a//2)+9*(a%2)) for a,n in enumerate(values))
    target.with_name('ay8910_init.vh').write_text(
        '// Generated by tools/make_psg.py; AY EBR startup contents.\n' +
        ',\n'.join(f'.INITVAL_{n:02X}("0x{(init>>(320*n))&((1<<320)-1):080X}")'
                   for n in range(32)) + '\n')
